csbproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('secureapp/', LoginView.as_view(template_name='secureapp/login.html', next_page='/secureapp/home')),
    path('secureapp/logout/', LogoutView.as_view(next_page='/secureapp')),
    path('secureapp/', include('secureapp.urls')),
]

secureapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'secureapp'
urlpatterns = [
    path('home', views.homeView.as_view(), name='home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:notice_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
]

secureapp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Notice(models.Model):
    notice_title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('date published (YYYY-MM-DD)')
    
    def __str__(self):
        return self.notice_title
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
class Comment(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    commenttext = models.CharField('Comment',max_length=2000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.commenttext

secureapp/forms.py
from django import forms
from .models import Notice, Comment

class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['notice_title', 'description', 'pub_date']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['commenttext']
        

secureapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Notice, Comment, Choice
from django.template import loader
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .forms import CommentForm, NoticeForm


def loginView(request):
    if request.user.is_authenticated:
        return render(request, 'secureapp/login.html')
    else:
        return render(request, 'secureapp/login.html')
    
#FLAW: Insecure design
#   As the app stands now, if the attacker knows the URL the attacker can see everything in the app
#   without loggin in. If the app includes sensitive information, all the info might be leaked.
#   
#
#   To fix the flaw, uncomment the lines 61, 65, 66, 75, 93 and 94. After uncommenting these lines
#   if user is not logged in (and not authenticated) the app redirects to the login page.


class homeView(generic.ListView):
    template_name = 'secureapp/home.html'
    context_object_name = 'notice_list'

    def get_queryset(self):
        return Notice.objects.order_by('-pub_date')
    
    #FLAW: CSRF
    #   Without CSRF-protection, it is possible to access data as an authenticated
    #   user that should not be accessible. CSRF-tokens are already added to .html -files.
    #   
    #   To fix the flaw, comment lines with @csrf_exempt (lines 43, 97 and 118) and check that forms in .html -files have CSRF-tokens.
    
    @csrf_exempt
    def post(self, request, *args, **kwargs):
        form = NoticeForm(request.POST)

        if request.user.is_authenticated:
            print(form)
            if form.is_valid():
                newn = form.save(commit=False)
                newn.save() # new notice added
                choice1 = Choice(notice = newn, choice_text = 'Good notice', votes=0)
                choice1.save()
                choice2 = Choice(notice = newn, choice_text = 'Irrelevant notice', votes=0)
                choice2.save() # added the voting choices
            return self.get(request, *args, **kwargs)
        else:
            messages.error(request, 'Log in to add notice!')
            return redirect('../secureapp')
        
    def get(self, request, *args, **kwargs):
        #if request.user.is_authenticated:      #Uncomment to fix the insecure design -flaw
            notices = Notice.objects.order_by('-pub_date')
            form = NoticeForm()
            return render(request, self.template_name, {'notice_list': notices, 'form': form})
        #else:                                  #Uncomment to fix the insecure design -flaw
        #    return redirect('../secureapp')    #Uncomment to fix the insecure design -flaw



class DetailView(generic.DetailView):
    model = Notice
    template_name = 'secureapp/details.html'
 
    def get(self, request, *args, **kwargs):
        #if request.user.is_authenticated: #Uncomment to fix the insecure design -flaw
            n = self.get_object()
        
            #FLAW: (SQL-)injection 
            #   We can use Djangos built in option to filter data to avoid injection.
            #   Data should be filtered (or validated) before reaching the database to avoid attacker
            #   having access directly to the database.
            #   To fix the flaw, uncomment the line 85 and comment lines 87-90.
            
            #comments = Comment.objects.filter(notice=n)
        
            comments = Comment.objects.all()
            sqlq = request.GET.get('search')
            if sqlq:
                comments = Comment.objects.raw("SELECT * FROM Comment WHERE title LIKE '%{}%'".format(sqlq))
            
            form = CommentForm()
            return render(request, self.template_name, {'notice': n, 'comments': comments, 'form': form})
        #else:                          #Uncomment to fix the insecure design -flaw
        #    return redirect('../')     #Uncomment to fix the insecure design -flaw
    
    @csrf_exempt
    def post(self, request, *args, **kwargs):
        notice = self.get_object()
        form = CommentForm(request.POST)

        if request.user.is_authenticated:
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.user = request.user
                new_comment.notice = notice
                new_comment.save()
            return self.get(request, *args, **kwargs)
        else:
            messages.error(request, 'Log in to comment!')
            return redirect('../')
 

class ResultsView(generic.DetailView):
    model = Notice
    template_name = 'secureapp/results.html'

@csrf_exempt
def vote(request, notice_id):
    nn = get_object_or_404(Notice, pk = notice_id)
    try:
        selected_choice = nn.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'secureapp/details.html',
{
    'notice': nn,
    'error_message': "You didn't select a choice."
})
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('secureapp:results', args=(notice_id,)))
    

secureapp/templates/secureapp/details.html
<!DOCTYPE html>
<head>
    <title>The Secure App: Notice</title>
</head>

<h1>{{ notice.notice_title }}</h1>

<a href="{% url 'secureapp:home'%}">To the home page</a>

<p>Logged in as a {{user}}</p>

<p>Description:{{ notice.description }}</p>

<h3>Vote, was this a good notice?</h3>
<form action="{% url 'secureapp:vote' notice.id %}" method="post">
    {% csrf_token %} <!--Already added to fix the CSRF flaw to keep app working-->
    {% for choice in notice.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

{% block content %}
<h2>Comments about the topic:</h2>    
{% for comment in comments %}
    {%if comment.notice.id == notice.id %}
    <p>{{ comment.user.username }}: {{comment.commenttext }}</p>
    {%endif%}
{% endfor %}

<h3>Add comment:</h3>
<form method="post" action="{% url 'secureapp:detail' notice.id %}">
    {% csrf_token %} <!--Already added to fix the CSRF flaw to keep app working-->
    {{ form.as_p }}
    <button type="submit">Add comment</button>
</form>
{% endblock %}

secureapp/templates/secureapp/home.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>The Secure App</title>
</head>

<h1>The secure app</h1>
<p>List of all cyber security notices in this app: </p>
{% if notice_list %}
    <ul>
    {% for notice in notice_list %}
    {% csrf_token %} <!--Already added to fix the CSRF flaw to keep app working-->
        <li><a href="{% url 'secureapp:detail' notice.id %}">{{ notice.notice_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No notices are available.</p>
{% endif %}

{% block content %}
<form method="post" action="{% url 'secureapp:home' %}">
    {% csrf_token %} <!--Already added to fix the CSRF flaw to keep app working-->
    {{ form.as_p }}
    <button type="submit">Add notice</button>
</form>
{% endblock %}

<p>Logged in as: {{user}}</p>
<form action='logout/' method="POST">
    {% csrf_token %}
    <input type="submit" value="Logout"/>
</form>

secureapp/templates/secureapp/login.html
<h2>Login</h2>
<p>Login to continue to the secure app.</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

secureapp/templates/secureapp/results.html
<body>
    <h1>{{ notice.notice_title }}</h1>

    <ul>
    {% for choice in notice.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    
</body>
<a href="{% url 'secureapp:detail' notice.id %}">To the notice page</a>

<a href="{% url 'secureapp:home'%}">To the home page</a>